### ISSUE TITLE
A suggestion about recursive function

### ISSUE THREAD

**Issue by allaev** [devbuilt/Algorithms-and-Data-Structures#1]
A small proposal on [capitalizeWords](https://github.com/devbuilt/Algorithms-and-Data-Structures/blob/master/capitalizeWords.js) recursive function.
Even though your implementation is short and elegant, but that does not involve a recursion.

So I would suggest the code below:
```
function capitalizeWords (array) {
  if (array.length === 1) {
    return [array[0].toUpperCase()];
  }
  let res = capitalizeWords(array.slice(0, -1));
  res.push(array.slice(array.length-1)[0].toUpperCase());
  return res;
}
```
Thanks.

**Comment by devbuilt** [comment]
Thanks for the input! Just updated the recursive solution for this Algo.
